/** Auto-generated by scripts/sync-cube-config.mjs — do not edit by hand. */
window.MBOX_CUBE_EFFECT_FRAMEWORK = {
  "safetyWeight": 7,
  "qualityWeight": 3,
  "parallaxAllowedPhases": [
    "showcase_hold"
  ],
  "parallaxPeakMax": 0.34,
  "parallaxFgMulVolumax": 0.095,
  "parallaxBgMulVolumax": 0.082,
  "facePhotoZ": 0.018,
  "faceBgZ": -0.022,
  "focusPulseZMax": 0.048,
  "faceUvInset": 0.038,
  "faceContentScale": 0.94,
  "volumaxAlphaTest": 0.08,
  "originalPlateBlurPx": 22
};
window.MBOX_CUBE_PRESENTATION_DEFAULTS = {
  "presentationEffectId": "cube_focus",
  "framePresetId": "rose_gold",
  "customFrameColor": "",
  "backgroundTheme": "original",
  "backgroundPlateTheme": "original",
  "particleTheme": "none",
  "bgmTrackId": "none",
  "hologramMode": false,
  "voluMaxDepthEnabled": false,
  "voluMaxFxEnabled": false,
  "voluMaxAutoPrepareLayers": false,
  "voluMaxAiForegroundCutout": true,
  "cubeRotationMode": "yaw_cw",
  "fanSpeed": 1
};
