export type FanBladeOrnamentKind =
  | "rose"
  | "pearl"
  | "leaf"
  | "filigree"
  | "star"
  | "sparkle";

/** Vertex model: Nano Banana Pro (Gemini 3 Pro Image). */
export const DEFAULT_ORNAMENT_IMAGE_MODEL = "gemini-3-pro-image";

export const FAN_BLADE_ORNAMENT_KINDS = [
  "rose",
  "pearl",
  "leaf",
  "filigree",
  "star",
  "sparkle",
] as const satisfies readonly FanBladeOrnamentKind[];

/** Public web path (Vite `base: "./"`). Files generated by scripts/generate-fan-blade-ornament-assets.mjs */
export const FAN_BLADE_ORNAMENT_ASSET_DIR = "./assets/fan-blade-ornaments";

export function fanBladeOrnamentAssetUrl(
  kind: FanBladeOrnamentKind,
  baseDir = FAN_BLADE_ORNAMENT_ASSET_DIR
): string {
  return `${baseDir}/${kind}.png`;
}

/** Nano Banana Pro prompts — wedding fan-blade ring ornaments, transparent PNG. */
export const FAN_BLADE_ORNAMENT_GENERATION_PROMPTS: Record<FanBladeOrnamentKind, string> = {
  rose:
    "Extreme close-up of a single blush pink wedding rose flower head only, petals filling the frame, no stem no leaves no shadow, photorealistic, isolated on fully transparent background, no text, centered, square canvas",
  pearl:
    "Single lustrous white wedding pearl with soft iridescent highlight, 3D jewelry render, isolated on fully transparent background, gentle shadow beneath, no text, centered, square canvas",
  leaf:
    "Pair of elegant sage green eucalyptus wedding leaves, botanical illustration with soft 3D volume, isolated on fully transparent background, subtle shadow, no text, centered, square canvas",
  filigree:
    "Ornate antique gold filigree wedding ornament curl, baroque luxury metal scroll, 3D render with specular highlights, isolated on fully transparent background, no text, centered, square canvas",
  star:
    "Small refined gold six-point wedding star charm with soft glow, 3D jewelry render, isolated on fully transparent background, no text, centered, square canvas",
  sparkle:
    "Delicate gold diamond sparkle burst, four-point star lens flare, wedding luxury accent, isolated on fully transparent background, no text, centered, square canvas",
};
